# A string used to distinguish different Supabase projects on the same host. Defaults to the
# working directory name when running `supabase init`.
project_id = "oficialgvc"

[api]
port = 54321
# Extra comma-separated CORS origins to allow requests from.
# cors_origins = ["http://localhost:3000"]

[db]
port = 54322
# The database major version to use. This has to be the same as your remote database's. Run `SHOW
# server_version;` on the remote database to check.
major_version = 15

[db.pooler]
enabled = false
port = 54329
pool_mode = "transaction"
default_pool_size = 20

[edge_runtime]
enabled = true
port = 54324

[functions.public-submit-agendamento]
verify_jwt = false

[functions.create-user]
verify_jwt = false

[functions.update-user-password]
verify_jwt = false

[functions.send-agendamento-email]
verify_jwt = false

[functions.auto-checkout]
verify_jwt = false

[functions.register-audit]
verify_jwt = false

[functions.export-backup]
verify_jwt = false
